name: benchmark_test
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  objectbox: 1.7.2
  objectbox_flutter_libs: 1.7.2

  isar: 3.0.5
  isar_flutter_libs: 3.0.5

  drift: 2.5.0

  hive: 2.2.3

  sqflite: 2.2.4+1

  realm: 1.0.1

  path_provider: 2.0.12
  path: 1.8.3
  random_string: 2.3.1
  fl_chart: 0.60.0
  logging: 1.1.1
  file: 6.1.4
  platform: 3.1.0

dev_dependencies:
  flutter_lints: 2.0.1
  build_runner: 2.3.3
  isar_generator: 3.0.5
  objectbox_generator: 1.7.2
  drift_dev: 2.5.2
  hive_generator: any


flutter:

  uses-material-design: true